# -*- coding: utf-8 -*-
"""AI_DEVOIR_A*.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14BdfhgfZyKRYl_7pquqRbRlg4ECwFKvW
"""

import numpy as np
import heapq
import random

import numpy as np

class Taquin:
    def __init__(self, size = 3, initial = None):
        """
        Initialize a new Taquin game board.
        Examples
        --------
        # >>> t = Taquin()
        # >>> print(t)
        ...
        """
        # set the board size
        self.size = size
        self.final = np.arange(1, self.size**2+1)
        self.final[-1] = 0

        self.final = self.final.reshape(self.size, self.size)
        self.final = self.tostring(self.final)

        self.alt_initial = self.final#.copy()

        if initial is None:
            # generate a random board if no initial state is specified
            self.board = self.alt_initial
            self.board = self.reverse()
        # use the specified initial state
        else:
            self.board = initial


    def asgrid(self, board):
      # board = board.copy()
      if isinstance(board, str):
        board = board.split('.')
        grid = [int(c) for c in board]
        grid = np.array(grid)
      elif isinstance(board,np.ndarray ):
        grid = np.array(board)
      grid = grid.reshape((self.size, self.size))
      return grid

    def tostring(self, grid):
        grid = grid.flatten()
        string = [str(d) for d in grid]
        return '.'.join(string)

    def __str__(self):
        # return str(self.asgrid(self.board))
        # return self.board
        grid = self.asgrid(self.board)
        s=''
        cell_width = int(np.ceil(np.log10(self.size**2)))
        for i in range(self.size):
            p = '|'+f'{str(" | ")}'.join([f'{str(grid[i,j]):0>{cell_width}}' for j in range(self.size)])+'|'
            s = f'\n{(self.size*(cell_width+3)-1)*"-"}\n'.join([s, p])
        return f'\n{(self.size*(cell_width+3)-1)*"-"}\n'.join([s, ''])
    def wheretomove(self):
        grid = self.asgrid(self.board)
        empty_pos = np.argwhere(grid == 0)
        y,x = empty_pos[0, 0],empty_pos[0,1]

        children = []
        if y-1 in range(self.size):
            # move up U
            copy = grid.copy()
            copy[y,x] = copy[y-1,x]
            copy[y-1,x] = 0
            children.append(self.tostring(copy))
        if x-1 in range(self.size):
            # move left L
            copy = grid.copy()
            copy[y,x] = copy[y,x-1]
            copy[y,x-1] = 0
            children.append(self.tostring(copy))
        if y+1 in range(self.size):
            # move down D
            copy = grid.copy()
            copy[y,x] = copy[y+1,x]
            copy[y+1,x] = 0
            children.append(self.tostring(copy))
        if x+1 in range(self.size):
            # move right R
            copy = grid.copy()
            copy[y,x] = copy[y,x+1]
            copy[y,x+1] = 0
            children.append(self.tostring(copy))
        return   children
    def reverse(self):
      copy = self.asgrid(self.board)
      for _ in range(100): # Increased for better shuffle
          empty_pos = np.argwhere(copy == 0)[0]
          y, x = empty_pos

          moves = []
          if y > 0: moves.append((-1, 0)) # Up
          if y < self.size - 1: moves.append((1, 0)) # Down
          if x > 0: moves.append((0, -1)) # Left
          if x < self.size - 1: moves.append((0, 1)) # Right

          dy, dx = moves[np.random.randint(len(moves))]
          copy[y, x], copy[y+dy, x+dx] = copy[y+dy, x+dx], copy[y, x]

      return self.tostring(copy)


    def isfinal(self):
        return self.board == self.final

t=Taquin(5, )
print(t)

class algoBFS():
    def __init__(self, size = 3):
        self.size = size

    def get_path(self, sol)  :
        if sol is None:
            return ''
        else:
            taquin = Taquin(self.size, sol)
            return self.get_path(self.parents[sol])+'\n'+str(taquin)
    def get_depth(self, sol)  :
        if sol is None:
            return 0
        else:
            taquin = Taquin(self.size, sol)
            return 1+self.get_depth(self.parents[sol])
    def search(self):
        self.free_nodes = []
        self.closed_nodes = []
        self.parents = {}
        taquin = Taquin(self.size)
        self.free_nodes.append(taquin.board)
        self.parents[taquin.board] = None
        success = False
        i = 0
        while self.free_nodes != [] and not success :
            i +=1
            current = self.free_nodes.pop(0)
            self.closed_nodes.append(current)

            taquin = Taquin(self.size, current)
            if taquin.isfinal():
                success = True
            else:
                children = taquin.wheretomove()
                for child in children:
                    if child not in self.closed_nodes and child not in self.free_nodes:
                        self.free_nodes.append(child)
                        self.parents[child] = taquin.board

        if success:
            print('success')
            print(len(self.parents))
            print(self.get_path(taquin.board))
            print(self.get_depth(taquin.board))
        print(i)

a1 = algoBFS(2)
a1.search()

a1 = algoBFS(3)
a1.search()

"""<div style="background-color:#e8f5e9; padding:12px; border-left:6px solid #2e7d32;">
<b>Partie Personne 3 : Implémentation de la structure de données A*</b><br><br>
Dans cette partie, nous proposons une classe <code>algoAstar</code> basée sur l’algorithme A*.
La liste des nœuds ouverts est remplacée par une file de priorité <code>heapq</code>.
Les nœuds fermés sont stockés dans un <code>set</code> pour accélérer les tests d’appartenance.
Le coût réel <code>g(n)</code> est mémorisé pour chaque état.
Dans cette première version, l’heuristique utilisée est provisoirement <code>h(n)=0</code>.
</div>
"""

import heapq

class algoAstar:
    def __init__(self, size=3):
        self.size = size

    def heuristic(self, state):
        return 0

    def get_path(self, sol):
        if sol is None:
            return ''
        else:
            taquin = Taquin(self.size, sol)
            return self.get_path(self.parents[sol]["parent"]) + '\n' + str(taquin)

    def get_depth(self, sol):
        if sol is None:
            return 0
        else:
            return 1 + self.get_depth(self.parents[sol]["parent"])

    def search(self):
        self.open_heap = []
        self.closed_nodes = set()
        self.parents = {}

        taquin = Taquin(self.size)
        start = taquin.board

        self.parents[start] = {"parent": None, "g": 0}

        f_start = self.parents[start]["g"] + self.heuristic(start)
        counter = 0
        heapq.heappush(self.open_heap, (f_start, counter, start))

        success = False
        i = 0
        solution = None

        while self.open_heap and not success:
            current_f, _, current = heapq.heappop(self.open_heap)

            if current in self.closed_nodes:
                continue

            i += 1
            self.closed_nodes.add(current)

            taquin = Taquin(self.size, current)

            if taquin.isfinal():
                success = True
                solution = current
            else:
                children = taquin.wheretomove()

                for child in children:
                    if child in self.closed_nodes:
                        continue

                    tentative_g = self.parents[current]["g"] + 1

                    if (child not in self.parents) or (tentative_g < self.parents[child]["g"]):
                        self.parents[child] = {"parent": current, "g": tentative_g}

                        f_child = tentative_g + self.heuristic(child)
                        counter += 1
                        heapq.heappush(self.open_heap, (f_child, counter, child))

        if success:
            print("success")
            print("Nombre de noeuds mémorisés :", len(self.parents))
            print(self.get_path(solution))
            print("Profondeur :", self.get_depth(solution) - 1)

        print("Noeuds explorés i =", i)

"""<div style="background-color:#e3f2fd; padding:12px; border-left:6px solid #1565c0;">
<b>Choix techniques</b><br><br>
<ul>
  <li><code>open_heap</code> remplace <code>free_nodes</code> pour extraire toujours le nœud de plus petit coût estimé.</li>
  <li><code>closed_nodes</code> est un <code>set</code> pour obtenir une recherche en temps moyen <code>O(1)</code>.</li>
  <li><code>parents</code> mémorise le parent de chaque état pour reconstruire le chemin final.</li>
  <li><code>g_cost</code> stocke le coût réel depuis l’état initial.</li>
</ul>
Cette structure prépare la classe à recevoir plus tard une vraie heuristique comme Manhattan.
</div>
"""

a = algoAstar(2)
a.search()

a = algoAstar(3)
a.search()

"""<div style="background-color:#e8f5e9; padding:12px; border-left:6px solid #2e7d32;">
<b>Validation de la structure A*</b><br><br>
La classe <code>algoAstar</code> a été testée avec succès sur des exemples de taquin 2x2 et 3x3.
La structure demandée a été mise en place :
<ul>
  <li>file de priorité pour les nœuds ouverts,</li>
  <li>ensemble de nœuds fermés,</li>
  <li>stockage du coût réel <code>g(n)</code>,</li>
  <li>reconstruction du chemin solution.</li>
</ul>
Dans cette première version, l’heuristique utilisée est provisoirement <code>h(n)=0</code>.
La classe est donc prête à recevoir ensuite les heuristiques du groupe.
</div>
"""